version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    volumes:
      - .docker-data/postgres-data:/var/lib/postgresql/data
      - .docker-data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_DB=foodbridge
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped

volumes:
  postgres-data: